apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCwY3C67MH7xyD+h4/9HwsaXkU4OA3g1mL8O8d5UY2xqnIKe+aqdhDJFNvGIWQEXshsNjpCzjtFq6J1f5hcrWrN3S/m34Anak+/D7LtKqMBRj0quFigwoCjslz0gqeeRVC4E4Hag5BSZ+6nIk20ntF3ruY28IOrT8XVqbZV5OBXb96WTNpIk7gbRJOb/hZm4V3DUXnK9syiIHT4tWFu+ukok0p1JE9zXy3+yaBDgkAR2aLxJY5LnVlNuUFSHHzRvqj0LkhZKxOjwW9du6SvB5UzWr/5jvB4/jcTLAqaMT+PT8Wl0e8DCzw+86LMIatqfiPn7BG4IhcRAR6UTzXf97q660/0EStXWEftNQ9t+Oj6gGQ1SWjfUMuhpHCSFcGOFSEmosOPVaKdABuIyddZZX7D3w1P5Pp1SatuuqHqdWA6o38InCfNSkiuqEuVvLqxuuWf/+9xeqsePE6VyCqbeMFvDwGA1cH+lXjUTatFuc2NAhLA2Beupl93raK+npU3nd10XxDyZJ1rUOSrN5zMrhZOtsY/k46i/sIjzml5/PyTk+YtES8aMGSCMJ6VrTLRg3ql67aAlwMHLdOMcnptWYBmihqE/uxJvXgmTYBkA14ptUn8C0tBO4tlFotrX6YIqTFmp07ZD92y7iTOVAFOGC3WvLlcOc4h4kzkKYEXkR7NbN8xW5uWJCTYyaPyrmjRTqS6v2c8JpCsDdsGgRzemNifTQaLPt3AtbBu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

